services:
  database:
    image: postgres:15
    container_name: pokemon_tcg_db
    environment:
      POSTGRES_DB: pokemon_tcg_db
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: pokemon_tcg_backend
    env_file:
      - ./Backend/src/config/.env
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./Backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: pokemon_tcg_frontend
    env_file:
      - ./Frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
