services:
  database:
    image: postgres:15
    container_name: pokemon_tcg_db
    environment:
      POSTGRES_DB: pokemon_tcg_db
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: pokemon_tcg_backend
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=pokemon_user
      - DB_PASSWORD=pokemon_pass123
      - DB_NAME=pokemon_tcg_db
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./Backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: pokemon_tcg_frontend
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=http://localhost:3000/api
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
